### PR TITLE
test: compile against the documented minimum Check version (fixes #91)

### LINKED ISSUE #91: make test fails with documented check version
Looks like the use of `ck_assert_uint_eq` would require at least check-devel 0.10.0: https://github.com/libcheck/check/commit/305371c21f7d865296a8e93791ad8a4f286b0b1a

RHEL 7 version of check is 0.9.9

Error:

```
DEBUG util.py:490:  BUILDSTDERR: check_cjose-check_concatkdf.o: In function `test_cjose_concatkdf_otherinfo_noextra':
DEBUG util.py:490:  BUILDSTDERR: /builddir/build/BUILD/cjose-0.6.1/test/check_concatkdf.c:98: undefined reference to `ck_assert_uint_eq'
DEBUG util.py:490:  BUILDSTDERR: check_cjose-check_concatkdf.o: In function `test_cjose_concatkdf_otherinfo_apuapv':
DEBUG util.py:490:  BUILDSTDERR: /builddir/build/BUILD/cjose-0.6.1/test/check_concatkdf.c:123: undefined reference to `ck_assert_uint_eq'
DEBUG util.py:490:  BUILDSTDERR: collect2: error: ld returned 1 exit status
```

### PR DESCRIPTION
**Pull request by zandbelt**
Fixes #91.

`test/check_concatkdf.c` uses `ck_assert_uint_eq()` in two places. That macro only exists in Check 0.10.0 and later, while the README, `CMakeLists.txt` and `configure.ac` all declare Check >= 0.9.4 as the minimum, so the test binary fails to link against the documented minimum (the report in #91 was RHEL 7's check 0.9.9). Replace both with a plain `ck_assert(otherinfoLen == N)`, which keeps the declared minimum true.

This is the same two-line change the OpenIDC/cjose fork has carried since 2022 (OpenIDC/cjose@30ef07c, linked from #91), cherry-picked with its original commit. The alternative would be to raise the documented minimum to 0.10.0 in the three places; this seemed the smaller change.

### Testing

Built with CMake (`-pedantic -Wall -Werror`) on Linux with GCC 15, OpenSSL 3.5.5, Jansson 2.14 and Check 0.15.2; `check_cjose` passes.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by TheStormN** [comment]
I think that now it is good time to bump the Check version to 0.12.0 for the 1.0.x release. 0.9 is really legacy one.

**Comment by TheStormN** [comment]
Closed in favor of #161
